/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author P0068839
 */
public class SearchAndEdit extends javax.swing.JFrame {
    
    
    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.
    private int originalEmpNum;
    /**
     * Creates new form AddNewEmployeeJFrame
     */
    public SearchAndEdit() {
        initComponents();
        jLabel8.setVisible(false);
        jTextField5.setVisible(false);
        jLabel7.setVisible(false);
        jTextField10.setVisible(false);
        jLabel6.setVisible(false);
        jTextField11.setVisible(false);
        jLabel5.setVisible(false);
        jTextField4.setVisible(false);
        toggleEmployeeTypeFields();
        jLabel4.setVisible(false); 
        // Setting all editing parts as invisible
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel1.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel13.setVisible(false);
        jLabel9.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton7.setVisible(false);
        jButton1.setVisible(false);

}
    
    
    public void setMainHT(MyHashTable theRefVal) {
        mainHT = theRefVal;
    }
int gender;
private void toggleEmployeeTypeFields() {
    if (jRadioButton6.isSelected()) {  
        jLabel5.setVisible(true);  
        jTextField4.setVisible(true);

        // Hide part-time fields
        jLabel8.setVisible(false);
        jTextField5.setVisible(false);
        jLabel7.setVisible(false);
        jTextField10.setVisible(false);
        jLabel6.setVisible(false);
        jTextField11.setVisible(false);
    } else if (jRadioButton7.isSelected()) {  // Part-Time selected
        // Show part-time fields
        jLabel8.setVisible(true);
        jTextField5.setVisible(true);
        jLabel7.setVisible(true);
        jTextField10.setVisible(true);
        jLabel6.setVisible(true);
        jTextField11.setVisible(true);

        // Hide salary fields
        jLabel5.setVisible(false);
        jTextField4.setVisible(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Employee Number");
        jLabel1.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jTextField1.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        jTextField1.setMinimumSize(new java.awt.Dimension(60, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 199, -1));

        jTextField2.setMinimumSize(new java.awt.Dimension(60, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 199, -1));

        jTextField3.setMinimumSize(new java.awt.Dimension(60, 20));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 200, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTheNewEmployee(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 550, 80, -1));

        jLabel4.setText("Employee added!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 265, -1));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAddNewEmployee(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 80, -1));

        jLabel9.setText("Deduction Rate");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, -1));

        jLabel10.setText("Location");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 55, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 200, -1));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Male");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabel11.setText("Gender");
        jLabel11.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, 22));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Edit Employee");
        jLabel12.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 16));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 170, 85));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Female");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Other");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("Employee Type");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Full-Time");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Part-Time");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jLabel8.setText("Weeks per year");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jLabel7.setText("Hours per week");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        jLabel6.setText("Hourly wage");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 60, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 60, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 60, -1));

        jTextField4.setToolTipText("Gross Annual Salary");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, -1));

        jLabel5.setText("Salary");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel14.setText("Employee Number:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, 20));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 530, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addTheNewEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTheNewEmployee
        // TODO add your handling code here:
        
        int theEmpNum = Integer.parseInt(jTextField3.getText());
    
    if (mainHT.employeeExists(theEmpNum) && theEmpNum != originalEmpNum) {
        jLabel4.setText("Error: Employee number already exists!");
        jLabel4.setVisible(true);
        return;
    }

    EmployeeInfo removedEmp = mainHT.removeEmployee(originalEmpNum);
    
    String theFirstName = jTextField1.getText();
    String theLastName = jTextField2.getText();
    double deductRate = Double.parseDouble(jTextField8.getText()) / 100;
    String strEmpLocation = jTextField9.getText();
    
    if (jRadioButton4.isSelected()) {
        gender = 0;
    } else if (jRadioButton5.isSelected()) {
        gender = 1;
    } else if (jRadioButton3.isSelected()) {
        gender = 2;
    }

    // full-time employee
    if (jRadioButton6.isSelected()) {
        String strSalary = jTextField4.getText();
        double dSalary = Double.parseDouble(strSalary);
        FTE theFTE = new FTE(theEmpNum, theFirstName, theLastName, gender, strEmpLocation, deductRate, dSalary);
        mainHT.addEmployee(theFTE);
    }

    // part-time employee
    if (jRadioButton7.isSelected()) {
        double wage = Double.parseDouble(jTextField11.getText());
        double hoursPerWeek = Double.parseDouble(jTextField10.getText());
        double weeksPerYear = Double.parseDouble(jTextField5.getText());
        String empLocation = jTextField9.getText();
        PTE thePTE = new PTE(theEmpNum, theFirstName, theLastName, gender, empLocation, deductRate, wage, hoursPerWeek, weeksPerYear);
        mainHT.addEmployee(thePTE);
    }

    jLabel4.setText("Employee: " + theFirstName + " " + theLastName + " has been updated!");       
    jLabel4.setVisible(true);

    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField9.setText("");
    jTextField8.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField10.setText("");
    jTextField11.setText("");
    jTextField6.setText("");
    buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    }//GEN-LAST:event_addTheNewEmployee

    
    private void exitAddNewEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAddNewEmployee
        // TODO add your handling code here:     
        this.dispose(); // Make this window disappear
    }//GEN-LAST:event_exitAddNewEmployee

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        toggleEmployeeTypeFields();
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        toggleEmployeeTypeFields();
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
        int empNum = Integer.parseInt(jTextField6.getText());
        originalEmpNum = empNum;
        EmployeeInfo searchedEmp = mainHT.getEmployee(empNum); 
        if (searchedEmp != null) {
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel1.setVisible(true);
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
            jLabel13.setVisible(true);
            jLabel9.setVisible(true);
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField8.setVisible(true);
            jTextField9.setVisible(true);
            jRadioButton5.setVisible(true);
            jRadioButton6.setVisible(true);
            jRadioButton3.setVisible(true);
            jRadioButton4.setVisible(true);
            jRadioButton7.setVisible(true);
            jButton1.setVisible(true);
            jLabel15.setText("You have searched employee: " + searchedEmp.getFirstName() + " "+searchedEmp.getLastName());
            jTextField1.setText(searchedEmp.getFirstName());
            jTextField2.setText(searchedEmp.getLastName());
            jTextField3.setText(String.valueOf(empNum));
            jTextField8.setText(String.valueOf(searchedEmp.getDeductRate()));
            jTextField9.setText(searchedEmp.getWorkLocation());
            if (searchedEmp.getGender() == "Male") {
                jRadioButton4.setSelected(true);
            } else if (searchedEmp.getGender() == "Female") {
                jRadioButton5.setSelected(true);
            } else {
                jRadioButton3.setSelected(true);
            }
            if (searchedEmp instanceof FTE) {
                jLabel5.setVisible(true);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jRadioButton6.setSelected(true);
                FTE theFTE = (FTE) searchedEmp;
                jTextField4.setText(String.valueOf(theFTE.getYearlySalary()));  
        } else if (searchedEmp instanceof PTE){
                jRadioButton7.setSelected(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                jLabel5.setVisible(false);
                jTextField5.setVisible(true);
                jTextField10.setVisible(true);
                jTextField11.setVisible(true);
                PTE thePTE = (PTE) searchedEmp;
                jTextField5.setText(String.valueOf(thePTE.getHourlyWage()));
                jTextField10.setText(String.valueOf(thePTE.getHoursPerWeek()));
                jTextField11.setText(String.valueOf(thePTE.getWeeksPerYear()));
            }
        else {
            jLabel15.setText("Employee not found.");
        }
    }
        } catch (NumberFormatException e) {
        jLabel15.setText("Invalid input. Please enter a valid employee number.");
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddNewEmployee_jFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
 
